##
SUFFIX = _gsl
CC = gcc
OPTS =

# uncomment to compile debug
DEBUG=-g -DFIEDLER_VECTOR #-DSPECTRAL_DEBUG
#DEBUG=-O3

# uncomment to compile with gsl
GSLFLAGS=-DHAVE_GSL -I/opt/local/include

# uncomment to compile with gsl library
GSLLIBS=-L/opt/local/lib -lgsl -lgslcblas ## macports
#GSLLIBS=/usr/lib64/libgsl.a /usr/lib64/libgslcblas.a -lm ## linux static
#GSLLIBS=-lgsl -lgslcblas ## linux


######################################################################
## shouldn't have to edit below
######################################################################
TARGETS = libspectral.a spectral_hk$(SUFFIX)
OBJS = b32.o sha1.o jacobi.o spectral.o periodic.o inchi.o features.o ring.o
CFLAGS= -Wall $(GSLFLAGS) $(DEBUG) $(OPTS)
LIBS = -lm $(GSLLIBS)

.c.o: $(OBJS)
	$(CC) $(CFLAGS) -c $<

all: $(TARGETS)

libspectral.a: $(OBJS)
	$(AR) -r $@ $(OBJS) 

spectral_hk$(SUFFIX): libspectral.a spectral_hk.c
	$(CC) $(CFLAGS) -o $@  spectral_hk.c libspectral.a $(LIBS)

pi$(SUFFIX): libspectral.a pi.c
	     $(CC) $(CFLAGS) -o $@ pi.c libspectral.a $(LIBS)

test: spectral_hk$(SUFFIX)
	./spectral_hk$(SUFFIX) examples.txt | sort

clean:
	$(RM) $(OBJS) $(TARGETS)
